Caoa-Montadora-de-Veiculos-Ltda/Protheus

- SIGACFG/Função/ZCFGF003.prw
Alteração do Escopo de Static Function para User Function das seguintes funções ,zBrwLeg,  zCopySZX e zBlqSZX
E alteração da Chamada para:
U_zBrwLeg 
U_zCopySZX
U_zBlqSZX
Pois para Rotinas que são chamadas em botões de Browse deve ser User Function.
> CFG001 - Alteração escopo das funções de  Static Function para User Function

- SIGAEIC/Funcao/CMVEIC01.prw
- SIGAEIC/Funcao/ZEICF021.PRW
Atualizado nos fontes ZEICF021.prw e CMVEIC01.prw ao integrar a Invoice Antecipada, gravar o a quantidade corretamente nas tabela EW4 e EW5, conforme está no arquivo CSV importado.
**Campos a serem Criados:** [EIC125_Campos.zip](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/11410020/EIC125_Campos.zip)
**Especificação dos Campos:** [EIC125-Campos a Criar.xlsx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/11410021/EIC125-Campos.a.Criar.xlsx)
**Termo de Aceite:** [GAP - EIC125 - Integração de Invoice Antecipada com quantidade a mais do que no CSV.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/11410022/GAP.-.EIC125.-.Integracao.de.Invoice.Antecipada.com.quantidade.a.mais.do.que.no.CSV.pdf)
> CHG0032299 - EIC125 - Integração de Invoice Antecipada com quantidade a mais do que no CSV

- Integracoes/SERPRO/CVMSER01.prw
Atualizado a Query que monta a Tabela SZ4 desvinculando da Tabela VV0, pois a mesmas informações estão na tabela SD2.
Atualização da rotina que gera o arquivo da SERPRO para utilizar a tabela SD2 como base e utilizar a VV0 para casos antigos.
**Termo de Aceite:** [GAP - SER102 - Integração SERPRO - Chassi - não aparece no Modulo Sigavei.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/11398449/GAP.-.SER102.-.Integracao.SERPRO.-.Chassi.-.nao.aparece.no.Modulo.Sigavei.pdf)
> CHG0032291 - SER102 - Atualizado a Query desvinculando da Tabela VV0

- Integracoes/SAP/Montadora/CMVSAP08.prw
-Melhoria para processar os registros do custo (Z7_ORIGEM = 'CMVCTBCUS' e 'CTBA102') com status Pendente (Z7_XSTATUS='P').
-Adicionado mensagem em caso de falha na conexão entre Protheus x SAP.
-Adicionar o relacionamento SZ7B.Z7_XCHAVE  = SZ7.Z7_XCHAVE na query para trazer os registros corretos
**Termo de aceite:** [GAP-SAP006 - Integração do Custo Protheus x SAP.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/11511648/GAP-SAP006.-.Integracao.do.Custo.Protheus.x.SAP.pdf)
> SAP006-A integração Protheus x SAP do Custo

- SIGAEIC/Funcao/ZEICF021.PRW
Acerto na Query de consulta de saldo para não retornar posições que não possuem mais saldo disponível.
Validação do saldo conforme a regra W5_PGI_NUM em branco e W3_FLUXO igual a 1, pegar o pegar o saldo da tabela SW5 e não da tabela SW3.
**Termo de Aceite:** 
[GAP - EIC128 - Integração de Invoice Antecipada com quantidade a mais do que no CSV.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/11511578/GAP.-.EIC128.-.Integracao.de.Invoice.Antecipada.com.quantidade.a.mais.do.que.no.CSV.pdf)
> EIC128 - Importa CSV da invoice antecipada  com o Saldo corretamente

- Integracoes/SAP/Montadora/CMVSAP08.prw
- Ponto de Entrada/MT094LOK_PE.PRW
Ao gerar o XML de integração com o SAP a TAG <textoCabecalhoDocumento> tem o tamanho máximo de 25 caracteres, o nome do Vendedor.
Foi limitado no fonte CMVSAP008.prw para 25 caracteres assim prevenindo erros futuros
> CHG0032426 - SAP007 - Erro de Schema do XML de envio ao SAP

- SIGAEIC/Funcao/GRVPO400.prw
Removido os Campos W3_FLUXO e W3_SEQ da consulta que pega as informações dos itens, para gravar na Capa da P.O.(SW2) e
as Informações no Pedido de Compa(SC7) corretamente.
*Termo de Entrega: * 
[GAP -EIC133-As PO's do tipo CBU não estão gravando o tipo de importação.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/11636609/GAP.-EIC133-As.PO.s.do.tipo.CBU.nao.estao.gravando.o.tipo.de.importacao.pdf)
> CHG0032442 - EIC133 - Removido os Campos W3_FLUXO e W3_SEQ da consulta na Gravação da Capa da PO

- SIGAFAT/Função/ZFATF014.PRW
Fonte: ZFATF014
Erro: Ao descredenciar ou bloquear o cliente o sistema não estava salvando.
Correção: Ajustado a função zF014ZERLC para desconsiderar o campo A1_XBLQVEN no update de limpeza dos campos.
> PEC061 - Erro ao descredenciar cliente - LC

- SIGAFAT/Função/nfesefaz.prw
Alterado para pegar a descrição do produto do cadastro de produto(SB1).
pois ao pegar a descrição da tabela SC6 - Item do Pedido de venda o qual esta com tamanho menor assim pegando a descrição incompleta.
Obs.: Futuramente será necessário analisar o impacto para aumentar o tamanho do campo de descrição da SC6 igualando a SB1.
> CHG0032462 - FAT120 - Alteração da descrição na Impressão da Danfe

- SIGAVEI/Relatorio/ZVEIR002.PRW
Na Consulta de Faturamento (ZVEIR002) na geração da consulta estava pegando o número do pedido de compra da Tabela SC6 o qual somente é preenchido pelo portal comercial.
Foi alterado para pegar o número da Tabela VRJ também, assim priorizando a Tabela VRJ e depois a SC6 assim pegando da tabela que estiver preenchido.
> CHG0032463 - VEI112 - Alteração para pegar o número do pedido da Tabela VRJ

- SIGAEIC/Funcao/ZEICF021.PRW
Ajustado o cálculo para pegar o valor unitário arredondando para 5 casas decimais os valores dos itens e arredondando para 2 casas decimais o total do cabeçalho da invoice.
[GAP - EIC134-Arredondamento de valores da Invoice Antecipada vs Embarque.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/11708423/GAP.-.EIC134-Arredondamento.de.valores.da.Invoice.Antecipada.vs.Embarque.pdf)
> CHG0032472- EIC134 - Arredondamento de valores da Invoice Antecipada vs Embarque

- SIGAPCP/Funcao/ZPCPF007.PRW
A rotina ZPCPF010 chama a rotina do Job ZPCPJ002 o qual chama as Rotinas do fonte ZPCPF007.prw o qual está ocorrendo o erro.
VV1010: DB error (Update): -29 File: VV1010 - Error : 1 - ORA-00001: unique constraint (ABDHDU_PROT.VV1010_UNQ) violated
Esse erro é provocado quando é utilizado uma numeração do campo VV1_CHAINT que já foi utilizado na tabela VV1 provocando erro de Chave Unica e assim derrubando o Job ZPCPJ002 provocando o reinicio do processo, desta forma extrapolando o tempo de processamento do JOB.
Foi incluído um tratamento para que a numeração disponibilizada pelo hardlock seja verificado se já foi utilizado e confirmar a numeração antes de usá-la assim evitando que o sistema disponibilize um número já utilizado e não confirmado para inclusão do Veículo, assim forçando a …
> CHG0032564 - PCP105 - Rotina backflush de veículos travando.

- SIGAPEC/Funcao/ZPECF023.prw
PEC010 | Importação de planilha de Produtos | Excluir local de recebimento
Fonte: ZPECF023
Erro: Estava considerando o local informado na planilha para subir os produtos.
Correção: Ajustado para considerar sempre o inicializador padrão do campo.
> PEC010 | Importação de planilha de Produtos | Excluir local de recebimento

- SIGAEIC/Funcao/ZEICF021.PRW
Foi acrescentada função para remover Caracteres Especiais na Importação das Invoices Antecipada nos campos:
Na Tabela EW5
EW5_XHOUSE
EW5_XNAVIO
EW5_XCASE
EW5_XCONT
EW5_XLOTE
Tabela SZM
ZM_NAVIO 
ZM_CONT
ZM_LOTE
ZM_CASE
ZM_UNIT
Pois Originalmente essa função só limpava o campo ZM_UNIT, e era removido os caracteres especiais na criação do arquivo CSV
> CHG0032601 | EIC003.006 | Remover Caracteres Especiais na Importação da Invoice Antecipada

- SIGAPEC/Funcao/ZPECF030.PRW
- SIGAPEC/Funcao/ZPECF032.prw
- SIGAPEC/Funcao/ZPECFUNA.PRW
Fonte: ZPECF030
Erro: Falta item Similar
Correção01: Incluido funcionalidade ZPECF30ITS na tela principal
Erro: Calculo de Saldo e de orçamento duplicando
Correção02: Ajustado Select na subquery para verificar B2_local, mostrar todos os armazens com saldos, e mostrar sempre armazém 11 mesmo sem saldo
Fonte: ZPECFUNA
Erro: Confirmação na consulta do orçamento errolog
Correção01: Criado funcionalidade para consulta de Orçamento MILAXTABELA e retirada antiga
Fonte: ZPECF032
Erro: Confirmação na consulta do orçamento errolog
Correção01: Alterado botão para consulta de Orçamento chamada fonte MILAXTABELA
> CHG0032597 | PEC004.001 | Ajuste itens similar

- Ponto de Entrada/EICDI154_PE.PRW
Foi incluído no fonte EICDI154_PE.prw o ponto de entrada **"GRAVACAO_SD1"**, o qual é chamado no momento da geração do Documento de Entrada pelo EIC, assim preenchendo o Array dos Itens do Documento com os campos customizados.
Pois neste ponto existe uma tabela temporária o qual é usado para gerar os itens do documento.
Ao Preencher os campos customizados nesse ponto, a area de trabalho esta posicionado no item corretamente para ser utilizado, assim preenchendo os campos  necessários para o endereçamento do unitizadores
[GAP045- Erro ao endereçar unitizador.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12088522/GAP045-.Erro.ao.enderecar.unitizador.pdf)
> CHG0032606 | EIC002.003 | Erro na gravacao das inf de importacao na nota de veiculo

- Ponto de Entrada/A261TOK_PE.prw
- Ponto de Entrada/MA261EST_PE.prw
- Ponto de Entrada/MT240EST_PE.prw
- Ponto de Entrada/MT241TOK_PE.prw
- Ponto de Entrada/OA180VLD_PE.prw
- SIGAEST/Função/ZESTF010.prw
Fontes:
A261TOK_PE.prw 
MA261EST_PE.prw
MT240EST_PE.prw
MT241TOK_PE.prw
OA180VLD_PE.prw
ZESTF010.prw
Motivo: Todos usuários conseguem fazer movimentações internas e transferências em todos armazéns, sendo necessário bloquear as movimentações internas e transferências manuais para armazéns utilizados pelo sistema em todas as filiais da empresa 2020.
Melhoria: Desenvolvimento de programas específicos para bloquear o acesso a todos os usuários. Os usuários com permissão podem ser liberados no Cadastro Rotinas x Acessos (Caoa) no SIGACFG pelo administrador do sistema.
> CHG0032610 | EST001 | Bloqueio movimentações e transferência em armazéns específicos (#GAP012)

- Integracoes/Autoware/Montadora/CMVAUT01.PRW
Foi verificado que erro na validação se o Cliente está Ativo ou Inativo.
onde o  campo A1_MSBLQL  for igual a 1 o cliente está Inativo e se for 2 ou vazio o cliente esta ativo
**Termo de Entraga**
[GAP047-Correção na validação do Bloqueio de Cliente.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12147565/GAP047-Correcao.na.validacao.do.Bloqueio.de.Cliente.pdf)
> Integração | Autoware 100.002 | Correção na validação do Bloqueio de Cliente (#GAP047)

- Integracoes/Autoware/Montadora/CMVAUT01.PRW
GAP048 | Ajuste no controle de numeração da Tabela SC5
Inclusão de controle de numeração, para verificar se o número do pedido já existe na tabela SC5 (Pedido de
Venda) e confirma sua utilização e pegando o próximo número disponível.
**Termo de Entrga** 
[GAP048 - Controle de Numeração na integração do Autoware..pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12152619/GAP048.-.Controle.de.Numeracao.na.integracao.do.Autoware.pdf)
> CHG0032627 | Integração | Autoware 100.003 | Ajuste no controle de numeração da Tabela SC5 (#GAP048)

- Ponto de Entrada/MT089CD_PE.prw
Foi criado o Parâmetro CMV_TPOPER, o qual deverá informar as operações que deverão ser executados no Padrão, o qual foi implementado no fonte  MT089CDP_PE.prw
O Parâmetro deverá ser criado nas duas empresas conforme abaixo. 
Anápolis
Parâmetro.:   CMV_TPOPER
Tipo...........:   Caracter 
Descrição..:  Tipo de Operação para ignora o PE MT089CD
Conteúdo..:  70|71
Barueri:
Parâmetro.:   CMV_TPOPER
Tipo...........:   Caracter 
Descrição..:  Tipo de Operação para ignora o PE MT089CD
Conteúdo..:   93
**Termo de Entraga**
[GAP044-Tes Inteligente.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12164668/GAP044-Tes.Inteligente.pdf)
> CHG0032631 | FIS004.001 | Adição dos tipos de operação 70, 71 e 93

- SIGAEST/Função/ZESTF011.prw
Ajusta o Custo dos Produtos os quais devem estar no arquivo .CSV com o seguinte Layout :
D3_TM;D3_EMISSAO;D3_PRODUTO;D3_LOCAL;D3_CUSTO1;D3_OBSERVA
No arquivo deverá conter só um tipo de movimento(TM) e uma Data que será a data do movimento.  Se tiver TM diferentes ou data diferente, o processo será encerrado cancelando o processamento.
**Tremo de Entrega**
[GAP050-Desenvolvimento de programa para importação de CSV com custo de produtos para ajuste.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12187845/GAP050-Desenvolvimento.de.programa.para.importacao.de.CSV.com.custo.de.produtos.para.ajuste.pdf)
> CHG0032636 | EST999.001 | Importação CSV para ajuste de custo massivo

- Integracoes/Autoware/Montadora/CMVAUT01.PRW
Foi ajustado para que nos dados vindo do XML seja preenchido com espaço em branco para que fique com o tamanho do campo conforme o dicionário, para evitar divergência na chave de pesquisa.
> CHG0032666 | Integração | Autoware 100.004 | | Ajuste nos espaços em branco

- SIGAPEC/Funcao/ZPECF030.PRW
Fonte: ZPECF030
Erro: Em alguns casos estava apresentando o valor de tabela de preço errado.
Correção: Ajustado o fonte para sempre buscar o preço do campo DA1_PRCVEN
> GAP061 | Ajuste do Preço de Tabela - Consulta Peças

- Ponto de Entrada/MT089CD_PE.prw
Alterado o Ponto de Entrada MT089CD_PE.prw, para tratar a busca da TES da Integração do Autoware do mesmo modo que é tratado pela VEIA060.
Devido a origem do Veiculo ser 6-ESTR-IMPORT DIR,SEM SIMILAR NAC,CONSTA NA LISTA CAMEX, pois normalmente é utilizado a origem 0 - Nacional ou 1 - Importado, o qual o Protheus já estava preparado
[GAP071 - TES Rede Importados.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12352146/GAP071.-.TES.Rede.Importados.pdf)
> CHG0032716 | FIS004.002 | Ajuste da TES na integração Autoware

- Integracoes/RgLog - SILT/ZWSR012.prw
Fonte: ZWSR012
Erro: Integração de Armazenagem não integra qdo saldo armz 02 maior que o campo Reserva Técnica no Cadastro do produto
Objetivo: Inclusão de regra para tratamento do controle de saldo armz 02
> CHG0032722 | Integração | RgLog 001.003 | Ajuste na armazenagem do produto ref ao armazem 02

- SIGAPEC/Funcao/ZPECFUNA.PRW
Fonte: ZPECFUNA
Erro: Integração de Pedidos do Autoware da Zona Franca, não está respeitando as exceções por Cliente e Estado no cadastro de TES Inteligente
Objetivo: Ajuste na regra que traz a TES Inteligente para as UFs de Zona Franca.
> CHG0032747 | PEC001.006 | Inclusao do orçamento para respeitar a operação da TES inteligente

- Ponto de Entrada/EICPO400_PE.prw
Fonte: EICPO400_PE.PRW
Melhoria: Incluído a opção de F4 para quando o Paramixb for igual a "ANTES_ELIMINA"
> CHG0032784 | EIC002.003 | Incluir F4 na tela de eliminar saldo da Purchase Order

- Ponto de Entrada/EICPO400_PE.prw
- SIGACOM/Função/CMVIMP01.prw
- SIGAEIC/Funcao/GRVPO400.prw
Fonte: EICPO400_PE.prw
Incluído ponto de entrada MVC "VAL_GRAVA_PO" o qual faz a validação antes da Gravação das Tabelas.
O qual validará se o Tipo de Importação foi informado na Tabela SW0 o qual é replicado para a Tabela SW2.
Fonte : GRVPO400.PRW
Incluído validação  se o campo da SW2 esta preenchido com o tipo de importação
Fonte : CMVIMP01.PRW
Incluído validação  se o campo da SW2 esta preenchido com o tipo de importação
[GAP084 - Preenchimento do Tipo de importação na Purchase Order.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12601874/GAP084.-.Preenchimento.do.Tipo.de.importacao.na.Purchase.Order.pdf)
> CHG0032818 | EIC002.004 | Tipo de importação não está sendo preenchido em algumas Purchase Order de importação

- SIGAPEC/Funcao/ZPECFUNA.PRW
Fonte: ZPECFUNA.PRW
Erro: Orçamentos do cliente 000229 01 entrando com operação 091
Objetivo: Corrigir query de TES inteligente para não considerar deletados
> CHG0032836 | Integração | Autoware 001.003 | Ajuste nas condições da query do Tipo de Operação

- Ponto de Entrada/MS520VLD_PE.PRW
- Ponto de Entrada/VX001CNF_PE.prw
Fontes: VX001CNF_PE e MS520VLD_PE
Erro: Não está permitindo cancelamento de NF "Não autorizada" e não está respeitando MV_SPEDEXC
Objetivo: Alterar regra dos PE para que permita cancelamento de NF não autorizadas e respeite o parâmetro de cancelamento extemporâneo
> CHG0032887 | FAT002.001 | Ajustar o cancelamento para respeitar o MV_SPEDEXC

- SIGAEIC/Funcao/ZEICF017.PRW
Atualização da Consulta do programa que pega as informações da DI o qual estava como base usando o Campo D1_XCONT.
Nos casos onde as mercadorias são transportadas por via aérea, não possuem contêiner assim o campo D1_XCONT ficando em branco. 
Foi alterado para usar o campo D1_XCONHEC, assim usando o número do Processo para achar a DI.
[GAP101- Algumas notas de importação, tem gerado a informação de DI errada nas notas filhas.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13395584/GAP101-.Algumas.notas.de.importacao.tem.gerado.a.informacao.de.DI.errada.nas.notas.filhas.pdf)
> CHG0033023 | EIC008.001 | Correção das informações da DI nas notas filhas

- SIGAACD/Função/ZACDF001.prw
Criado validação no fonte ZACDF001, para que bloqueie a movimentação por um tempo no coletor, assim evitando que coletores diferentes façam a mesma movimentação mais de uma vez.
[GAP107-Criar Validação para evitar duplicar movimento.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13491838/GAP107-Criar.Validacao.para.evitar.duplicar.movimento.pdf)
> CHG0033057 | ACD001.001 | Controle de leitura duplicada

- SIGAEIC/Funcao/CMVEIC01.prw
- SIGAEIC/Funcao/ZEICF021.PRW
Fonte: ZEICF021
--  Foi corrigido o cálculo do Total da Invoice para arredondar em 2 casas decimais o Valor Total do Item ao invés de truncar o valor.
Fonte: CMVEIC01
-- Correção nas String que estavam apresentando caracteres especiais na Tela deixando incompreensível as Descrições.
-- Erro provocado pelo Encoding utilizado ao Salvar o Arquivo, recomendo utilizar o Encoding Windows 1252 no VSCode.
[GAP108 - O valor total da CI aparece divergente no sistema - Invoice Antecipada.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13516926/GAP108.-.O.valor.total.da.CI.aparece.divergente.no.sistema.-.Invoice.Antecipada.pdf)
> CHG0033070 | EIC003.013 | O valor total da CI aparece divergente no sistema

- SIGAFIS/Relatorio/ZFISR001.prw
- SIGAFIS/Relatorio/ZFISR005.prw
- SIGAFIS/Relatorio/ZFISR008.prw
- SIGAFIS/Relatorio/ZFISR009.prw
- SIGAFIS/Relatorio/ZFISR011.prw
- SIGAFIS/Relatorio/ZFISR012.prw
- SIGAFIS/Relatorio/ZFISR015.prw
Chamado: INC0092943
Ao verificar os dados do Relatório com a Geração do XML da NF-e, foi verificado que no relatório o campo de Valor do Item é somente o campo D2_TOTAL.
Enquanto o valor do item na Geração do XML é composto pela seguinte regra
Se (Não for Zona Franca)
--> D2_TOTAL + D2_DESCON + D2_DESCZFR - D2_VRDICMS
Senão
--> ( D2_TOTAL + D2_DESCON + D2_DESCZFR ) - ( D2_DESCZFP + D2_DESCZFC + D2_VRDICMS)
Foi acrescentado a mesma regra no relatório para corrigir o cálculo do valor do item que estava com divergência.
--
Ajustado a Divergência na despesa e desconto, o qual estava pegando do Cabeçalho do pedido, agora está pegando o desconto do Item da Nota fiscal (SD2)
--
Chamado: INC0101871
Ajustado o valor duplicado, pois estava gerando o valor de ISS no campo de INSS, foi corrigido para …
> CHG0033088 | FIS002.003 | Correção no Calculo do valor do item

- Integracoes/RgLog - SILT/ZWSR010.PRW
Foi detectado que que a tag de Deposito está com tamanho excessivo o qual deveria ter no máximo 5 caracteres, foi feito o tratamento para remover os espaços em branco antes de montar o Json para a Tag cd_Deposito
[GAP112-Inconsistência na estrutura do Json de integração de envio das Notas de Entrada para a RG LOG.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13685592/GAP112-Inconsistencia.na.estrutura.do.Json.de.integracao.de.envio.das.Notas.de.Entrada.para.a.RG.LOG.pdf)
> CHG0033113 | Integração | RgLog 004.002 | Ajuste na Tag Cd_Deposito

- Ponto de Entrada/SD1100I_PE.prw
- Ponto de Entrada/SD1140I_PE.prw
Desenvolvido rotina para verificar se o D1_NUMSEQ está duplicado na inclusão da Pré-Nota e na Classificação do Documento de entrada e corrigindo gerando um  numseq novo.
Foi criado o Ponto de Entrada SD1140I para validar na inclusão da Pré-Nota
Alterado o SD1100I para validar na Classificação da Pré Nota.
[GAP109 - Chave duplicada erro na geração da demanda.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13664709/GAP109.-.Chave.duplicada.erro.na.geracao.da.demanda.pdf)
> CHG0033106 | COM006 | Chave duplicada na classificação do Documento de Entrada

- Integracoes/MasterSaf/CMVMSF06.prw
INC0102380 : 
Manutenção SAFX108, quantidade produzida da OP dentro do período selecionado.
INC0103494 : 
Na extração da SAFX08, foi ajustado o campo de Item Nota Fiscal para continuar a sequência dos itens de forma numérica assim evitando a sequencia com Letras e Numeros
[GAP111-Manutenção SAFX108 e SAFX08.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13689264/GAP111-Manutencao.SAFX108.e.SAFX08.pdf)
> CHG0033114 | FIS003.007 | Ajuste no campo nota fiscal

- Ponto de Entrada/SD1140I_PE.prw
Foi verificado que o ponto de entrada SD1100I que chama a função fValiNUmSeq() para acertar o D1_NUMSEQ no fonte SD1140I_PE é executado depois da geração da Demanda do Unitizador.
Feita correção na função fValiNUmSeq() para atualiza a D0Q_NUMSEQ a Tabela de Demanda com o D1_NUMSEQ atualizado
[GAP113-Erro na Classificação de Processo (D0Q_NUMSEQ duplicado).pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13730591/GAP113-Erro.na.Classificacao.de.Processo.D0Q_NUMSEQ.duplicado.pdf)
> CHG0033131 | COM006.001 | Erro na Classificação de Processo, D0Q_NUMSEQ duplicado

- SIGAFIS/Relatorio/ZFISR001.prw
- SIGAFIS/Relatorio/ZFISR003.prw
- SIGAFIS/Relatorio/ZFISR008.prw
- SIGAFIS/Relatorio/ZFISR009.prw
- SIGAFIS/Relatorio/ZFISR010.prw
- SIGAFIS/Relatorio/ZFISR012.prw
- SIGAFIS/Relatorio/ZFISR015.prw
Ajustado o valor duplicado, pois estava gerando o valor de ISS no campo de ICMS, foi corrigido para que o ISS não seja gerado no campo de ICMS, para os Relatórios de Entrada, pois os Documento de Saída estão corretos.
> CHG0033173 | FIS002.005 | Trazendo valores de ISS nos campos de ICMS no Documento de Entrada

- SIGAMNT/Relatorios/ZMNTR001.PRW
Ajustado o Cabeçalho para aparecer o nome da filial por inteiro.
[GAP121 -Ajuste da Mensagem da Filial.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13877782/GAP121.-Ajuste.da.Mensagem.da.Filial.pdf)
> CHG0033192 | MNT002.001 | Ajuste na impressão do nome da filial

- SIGAFIS/Relatorio/ZFISR001.prw
- SIGAFIS/Relatorio/ZFISR003.prw
- SIGAFIS/Relatorio/ZFISR008.prw
- SIGAFIS/Relatorio/ZFISR009.prw
- SIGAFIS/Relatorio/ZFISR010.prw
- SIGAFIS/Relatorio/ZFISR012.prw
- SIGAFIS/Relatorio/ZFISR015.prw
Foi ajustado a Query do documento de entrada, pois o relacionamento do NCM com o Produto estava provocando a duplicação dos dados no relatório.
[GAP126-Está trazendo itens ou duplicando os itens com isso alterando o valor dá o valor da nota.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14141009/GAP126-Esta.trazendo.itens.ou.duplicando.os.itens.com.isso.alterando.o.valor.da.o.valor.da.nota.pdf)
> CHG0033285 | FIS002.006 | Ajuste na query para evitar a duplicidade de item

- SIGAMNT/Relatorios/ZMNTR001.PRW
Ajustado o Cabeçalho para aparecer o nome da filial inteira na página de Análise Preliminar de Risco.
[GAP129 - Realizar reparos nas descrições dos PDF's no verso da Ordens e Serviço.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14212501/GAP129.-.Realizar.reparos.nas.descricoes.dos.PDF.s.no.verso.da.Ordens.e.Servico.pdf)
> CHG0033304 | MNT002.002 | Ajuste na descrição da Ordens e Serviço

- SIGACOM/Função/ZCOMF032.prw
Alterado o fonte ZCOMF032, removendo o botão de “Alterar Comprador”, pois o mesmo não é utilizado.
[GAP123 -Erro na alteração do comprador na SC - tirar a funcionalidade da rotina .pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14210423/GAP123.-Erro.na.alteracao.do.comprador.na.SC.-.tirar.a.funcionalidade.da.rotina.pdf)
> CHG0033301 | COM007 | Retirada do botão "Alterar Comprador"

- SIGAMNT/Relatorios/ZMNTR002.prw
Solicitante: Micaellen Pereira Leal - CAOA
Desenvolvedor: A.Carlos - CAOA
Chamado:  CHG0033328 Melhoria no relatório sintético estoque/compras para alterar o valor de custo médio que estava buscando da tabela SB2, porém o custo médio do último fechamento consta na tabela SB9.
Inclusão do campo C7_PREÇO do último pedido de compra.
Incluídos campos:   C.Médio  e  Val.U.Compra
*Especificação Técnica: [Inclusão do campo de valor de última compra do produto MAN.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14409467/Inclusao.do.campo.de.valor.de.ultima.compra.do.produto.MAN.pdf)
*Manual Técnico: [Manual_Tecnico - GAP134 REL Cad Produto - Sintetico.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14409456/Manual_Tecnico.-.GAP134.REL.Cad.Produto.-.Si …
> CHG0033328 | MNT003 | Relatório Follow Up, ajuste de preço e custo

- SIGACTB/Funcao/ZCTBF001.PRW
Nome Original do GAP: Função FPESQVVP()
Descrição: Alterado a Função FPESQVVP(), que é responsável por pesquisar e trazer as informações da Tabela de Preço(VVP).
Foi alterado a ordenação da consulta e o preenchimento do array de retorno.
Desta forma ficando parecida com a função fTrazVVP() do fonte XML001.
Especificação Técnica:* Não possui
Manual Técnico:* Não Possui
Termo de Entrega:* Não Possui
> CHG0033347 | CTB001.002 | Ajuste no posicionamento na tabela VVP

- SIGAPEC/Funcao/ZPECF040.prw
Fonte : ZPECF040
ERRO : Não estava pegando produtos novos com saldos maior que zero estava classificando com I
Solução : Ajustado posicionamento para verificar primeiro produto Novo e depois o tipo I
> CHG0033421 | PEC013.002 | Não esta elegendo produtos novos com saldo para cálculo

- Integracoes/RgLog - SILT/ZWSR013.PRW
Alterado a função que converte a data DTOC para DTOS, pois quando é executado via Job a data é convertida para DD/MM/AA ao invés de DD/MM/AAAA como é via manual.
Pois a Função DTOS sempre traz a data no formato AAAAMMDD.
De:
cDataBase := 	Substr(DTOC(dDatabase),7,4) +'-'+;
Substr(DTOC(dDatabase),4,2) +'-'+;
Substr(DTOC(dDatabase),1,2)
Para: 
cDataBase := 	Substr(DTOS(dDatabase),1,4) +'-'+;
Substr(DTOS(dDatabase),5,2) +'-'+;
Substr(DTOS(dDatabase),7,2)
> CHG0033455 | Integração | RgLog 002.001 | Ajuste na função de conversão da data

- Ponto de Entrada/M410PVNF_PE.prw
Foi criado o Parâmetro:
CMV_FAT014 -- Código + Loja do Cliente que não passara pela validação de credito na Geração do Doc de Saida pelo Pedido de Venda
O qual será usado para BYPASS da análise de credito customizada, assim ignorando a análise para os clientes que estiver contido no parâmetro, caso tenha mais de um cliente separa por virgula os códigos.  
Exemplo:
COD001L1,COD002L1, ...
> CHG0033468 | FIN003.004 | Criação de parametro para ByPass em Lib do Credito

- SIGACOM/Relatorio/ZCOMR001.PRW
Incluído a somatória do frete no total do pedido de compra no lay-out de envio por email.
Fonte: ZCOMR001.prw
> CHG0033483 | COM003.002 | Inclusão do total do pedido + frete

- Ponto de Entrada/GRVMT112_PE.prw
- SIGACOM/Função/IMPCSVSC.PRW
Devido a diferenças nas Base de Dados entre Anápolis e Franco da Rocha, o campo A5_MSBLQL não existe na Base de Franco da Rocha
Foi criado validações para verificar se o campo A5_MSBLQL existe na base para validar se a amarração de produto x fornecedor esta com bloqueio.
> CHG0033525 | COM008.002 | Tratativa do campo A5_MSBLQL para Franco da Rocha

- SIGAACD/Função/ZACDF001.prw
Fonte: ZACDF001
Erro: Toda madrugada por volta de 1h os coletores estavam caindo.
Solução: Ajustado o fonte pois estava referenciando o campo errado na query
> CHG0033578 | ACD001.002 | Error log no acd de madrugada

- SIGAEIC/Funcao/ZEICF006.prw
GAP171 | Inclusão da aliquota de IPI no Cadastro de Produtos via gatilho - ZEICF006,
para auxiliar e evitar erro no cadastramento.
Descrição: Divergência no cadastramento do IPI no Produto.
Recurso CAOA
> CHG0033573 | EIC009.001 | Inclusao IPI no Cadastro de Produto

- Ponto de Entrada/GFEXFB18_PE.PRW
Foi declarado a variável nValor e atribuído o conteúdo da variável ParamIxb[1] que é o valor original do frete.
> CHG0033587 | GFE003 | Errorlog no calculo de frete

- SIGAPEC/Funcao/ZPECF008.PRW
Foram bloqueados os processos Hyundai na Empresa 02, porém existe a necessidade de tratar acertos de importações e o faturamento para RG de processos de reclamação que estavam parados por conta do corte da operação.
Desta forma foi retirado a trava da empresa 02 Franco da Rocha para rodar a marca Hyundai.
> CHG0033647 | PEC001.009 | Remover a trava da empresa 02 | Franco da Rocha para rodar a marca Hyundai.

- Integracoes/MasterSaf/CMVMSF06.prw
Alteração na função SAFX08 no fonte CMVMSF06.prw nas linhas 3082 e 4221, retirado campo SB1->B1_ORIGEM e substituído pelo SFT->FT_CLASFIS, assim a origem será considerada a NF e não do Produto.
> CHG0033761 | FIS003.008 | CST de fretes extraídos na safx incorretamente

- Integracoes/MasterSaf/CMVMSF06.prw
Alteração na função SAFX08 no fonte CMVMSF06.prw na linha 3077 adicionando a regra para somar o campo FT_DESCZFR a tag VLR_UNIT e VLR_ITEM.
> GAP205 | SAFX08 campo valor unitário p/ NFs que possui exoneração de ICMS ZFM

- Genericos/Funcao/ZGENFTE.prw
Alteração na função ZGENFTEPR do fonte ZGENFTE.prw, linhas 97, 224 e 254 para considerar a variável _cLocal conforme digitado no parâmetro pelo usuário, pois estava fixo no fonte como '11'
> GAP207 | Entradas das notas HMB (loja 90 módulo compras) , o armazém "local de Entrada" não está obedecendo o armazém indicado.

- Ponto de Entrada/EICDI500_PE.PRW
GAP209 - Alteração no fonte EICDI500_PE.prw , adicionado o PE "INV_CARREGA_SW8"  para gravar campo customizado W8_XCASE, W8_XLOTE e W8_XCONT
> EICDI500.001 | Campo D1_XCASE em branco quando o campo W8_XCASE estiver em branco

- Integracoes/SAP/ZGENSAP.prw
GAP211 - Integração Contas a Pagar Z7_SERORI="EIC"
Os títulos provenientes do módulo de importação (contas a pagar) não é para serem integrados no SAP.
Ajustado o fonte para que gera os registros na tabela SZ7 com o status de não integrado, para que não seja lido pelo job de integração.
Fonte: ZGENSAP.prw
> EIC003.006 | Integração Contas a Pagar Z7_SERORI="EIC"

- SIGAPEC/Funcao/ZPECF008.PRW
Ajustado a parte que faz a seleção e geração do BO para gerar os BO do produto original após substitui-lo pelo similar.
> RGLOG001.002 | O pedido foi atendido parcialmente não gerou B.O para item substituído

- Ponto de Entrada/COMCOLSD.prw
- Ponto de Entrada/M103PCIT.prw
GAP226-FIS003.010 | Extração de Relatório não esta extraindo o CST ICMS e CST IPI](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/pull/565#top)
O Relatório SAFX08 é um espelho dos livros Fiscais, a informação de Situação Tributária, não está sendo preenchida em alguns itens da Nota e consequentemente não é levada para o Livro Fiscal.
Conforme testes de validação isso ocorre quando há quebra de itens ao selecionar Pedido de Vendas, na inclusão da Nota, sendo pelo Documento de entrada ou pela Rotina de Monitor do TOTVS Colaboração.
Para que o campo Situação Tributária na NF, seja preenchido foram  desenvolvidos os Pontos de entrada M103PCIT.prw e COMCOLSD.prw, também criados gatilhos no campo DT_CLASFIS e DT_TES
, e também na extração das SAFX08 para carga. …
> FIS003.010 | Extração de Relatório não esta extraindo o CST ICMS e CST IPI

- SIGAFAT/Função/danfeii.prw
- SIGAFAT/Função/nfesefaz.prw
1 - Copiar RPO Produção para base a ser executada
2 - Criar parametro : MV_NT23004
Descrição: Parâmetro temporário para controle de datas da NT 2023.004.
Tipo: 1-Caracter
Cont. Por: 01/07/2024
3 - Aplicar Pacote : 24-07-18_ATUALIZACAO_12.1.2310_TSS_PROTHEUS_EXPEDICAO_CONTINUA
[24-07-18_ATUALIZACAO_12.1.2310_TSS_PROTHEUS_EXPEDICAO_CONTINUA.ZIP](https://github.com/user-attachments/files/16459762/24-07-18_ATUALIZACAO_12.1.2310_TSS_PROTHEUS_EXPEDICAO_CONTINUA.ZIP)
4 - Aplicar Pacote : PACOTE_DE_CORRECAO_18797903_DSERTSS1-22661_12.1.2310
[PACOTE_DE_CORRECAO_18797903_DSERTSS1-22661_12.1.2310.ZIP](https://github.com/user-attachments/files/16459764/PACOTE_DE_CORRECAO_18797903_DSERTSS1-22661_12.1.2310.ZIP)
5 - Recompilar fontes Danfeii.prw e NfeSefaz.prw
> GAP231 | Correção da ZFM - Desoneração - tag indDeduzDeson

- SIGAFAT/Função/nfesefaz.prw
GAP233 | Correção da tag xped do XML para faturamento dos HRs
> GAP233 | Correção da tag xped do XML para faturamento dos HRs

- SIGAFAT/Função/nfesefaz.prw
GAP240 | Alteração na rotina NFESefaz.prw para desconsiderar a custom ização RetNT2005 quando houver somente Confis e Não Cofins ST.
> GAP240 | Alteração na rotina NFESefaz.prw para desconsiderar a custom ização RetNT2005 quando houver somente Confis e Não Cofins ST.

- Ponto de Entrada/EICDI154_PE.PRW
…
Ajuste na rotina EICDI154_PE.prw para considerar a posição correta no array e buscar o B1_LOCREC quando não houver numero de SC preenchido.
> GAP242 | Ao tentar emitir a nota fiscal de importação apresenta erro de Pedido invalido

- Ponto de Entrada/PEDVEI011_PE.prw
Realizada instrução para criação de uma exceção fiscal para compor o calculo, sempre considerando Grupo do Produto, UF do Cliente e Tipo do Pedido (exemplo: revendedor ou consumidor Final)
Ajuste na rotina PEDVEI011.prw para puxar a informação do Tipo do Pedido do SIGAVEI para o SIGAFAT... assim será considerado na exceção Fiscal cadastrada.
> GAP241 | Solução para que o grupo tributário não seja trocado

- SIGAFAT/Função/nfesefaz.prw
Alteração na rotina NFESefaz.prw para desconsiderar a customização RetNT2005 quando houver somente Cofins e Não Cofins ST
> GAP240 | Alteração na rotina NFESefaz.prw para desconsiderar a customização RetNT2005 quando houver somente Cofins e Não Cofins ST

- SIGAPEC/Classes/SaldoCAOAPEC.PRW
- SIGAPEC/Funcao/ZPECF008.PRW
- SIGAPEC/Funcao/ZPECFUNA.PRW
INC0117653 | A onda de picking não está considerando todas as possibilidades de similaridade.
Ajustado para selecionar o produto similar que contiver maior saldo disponível
INC0118040 | Quando item é substituído, está ocorrendo a tentativa de movimentação dele e a soma da qde no substituto.
Quando Ocorrer a substituição total do item, o mesmo será excluído do orçamento, para não interferir na soma dos itens.
> GAP248 | Melhoria na Onda para Itens Similar e quantidade de Itens Substituto

- Ponto de Entrada/PEDVEI011_PE.prw
- SIGAFAT/Função/nfesefaz.prw
Inclusão das TAGS No XML FCI, Pedido, Item Pedido
Como solução Paliativa emergencial, alteração no fonte NFESefaz.prw para adicionar as regras :
1.           Quando campo C6_NUMPCOM e C6_ITEMPC não estiverem preenchidos e o cliente for 000008/05 e TES 801 forçar o preenchimento da TAG xPed = 5500012312 e nItemPed = 20
2.           Quando campo C6_NUMPCOM e C6_ITEMPC não estiverem preenchidos e o cliente for 000008/05 e TES 802 forçar o preenchimento da TAG xPed = 5500012312 e nItemPed = 10
3.           Quando campo D2_FCICOD não estiver preenchido e o cliente for 000008/05 e TES 801 forçar o preenchimento da TAG  nFCI = D4746E77-0A66-4782-B107-864BBEBE3A68"
Como solução definitiva:
1.          Criar o campo VRJ_XITEMPC, que será preenchido no cabeçalho do 'Pedido Montadora', campo criado …
> GAP250 | Inclusão das TAGS No XML FCI, Pedido, Item Pedido

- SIGAFAT/Função/nfesefaz.prw
Solução:
Inclusão das TAGS No XML FCI, Pedido, Item Pedido
Como solução Paliativa emergencial, alteração no fonte NFESefaz.prw para adicionar as regras :
1.           Quando campo C6_NUMPCOM e C6_ITEMPC não estiverem preenchidos e o cliente for 000008/05 e TES 801 forçar o preenchimento da TAG xPed = 5500012312 e nItemPed = 20
2.           Quando campo C6_NUMPCOM e C6_ITEMPC não estiverem preenchidos e o cliente for 000008/05 e TES 802 forçar o preenchimento da TAG xPed = 5500012312 e nItemPed = 10
3.           Quando campo D2_FCICOD não estiver preenchido e o cliente for 000008/05 e TES 801 forçar o preenchimento da TAG  nFCI = D4746E77-0A66-4782-B107-864BBEBE3A68"
Como solução definitiva:
1.          Criar o campo VRJ_XITEMPC, que será preenchido no cabeçalho do 'Pedido Montadora', …
> GAP250.1 | Inclusão das TAGS No XML FCI, Pedido, Item Pedido

- SIGAFAT/Função/nfesefaz.prw
Inclusão das TAGS No XML FCI, Pedido, Item Pedido
Como solução Paliativa emergencial, alteração no fonte NFESefaz.prw para adicionar as regras :
Quando campo C6_NUMPCOM e C6_ITEMPC não estiverem preenchidos e o cliente for 000008/05 e TES 801 forçar o preenchimento da TAG xPed = 5500012312 e nItemPed = 20
Quando campo C6_NUMPCOM e C6_ITEMPC não estiverem preenchidos e o cliente for 000008/05 e TES 802 forçar o preenchimento da TAG xPed = 5500012312 e nItemPed = 10
Quando campo D2_FCICOD não estiver preenchido e o cliente for 000008/05 e TES 801 forçar o preenchimento da TAG  nFCI = D4746E77-0A66-4782-B107-864BBEBE3A68"
Como solução definitiva:
Criar o campo VRJ_XITEMPC, que será preenchido no cabeçalho do 'Pedido Montadora', campo criado no cabeçalho pois conforme levantado por Micaellen, …
> GAP250.2 | Inclusão das TAGS No XML FCI, Pedido, Item Pedido

- Ponto de Entrada/VEIA060CAOA_PE.prw
- SIGAFAT/Função/ZFATF019.prw
- SIGAVEI/Função/CMVVEI01.prw
- SIGAVEI/Função/CMVVEI02.prw
Não está calculando e deduzindo o valor da comissão e ICMS ST das vendas diretas e vendas PCD.
Alteração nas rotinas para preencher os campos % Comissão (VRK_XPECOM) e Valor Comissão (VRK_XVLCOM), conforme o tipo de venda (VRJ_TIPVEN), buscando o % de Comissão no cadastro de modelos (VV2_XCOM1 a VV2_XCOM6)
> GAP251 | Nao está calculando e deduzindo o valor da comissao e ICMS ST das vendas diretas e vendas PCD

- Integracoes/SAP/ZGENSAP.prw
Atualização da consulta para selecionar os movimentos contábil da origem MATA997.
Adicionar ao Parâmetro CAOASAP09A o conteúdo ’|MATA997' ao que já existe
> GAP253 | contabilizada, só que a nota fiscal não foi integrada ao SAP e também não aparece na tabela SZ7.

- SIGAFAT/Função/nfesefaz.prw
Criado o campo VRJ_XITEMPC e compilado o fonte PEDVEI011_PE.prw, conforme solicitados o Ticket INC0119963, para trazer a informação dos campos:
VRJ_PEDCOM para C6_NUMPCOM
VRJ_XITEMPC para C6_ITEMPC
Assim, realizada a alteração no fonte NFESefaz.prw para adicionar as regras :
1 - Quando campos C6_NUMPCOM e C6_ITEMPC não estiverem preenchidos e o cliente for 000008/05 e TES 802 forçar o preenchimento da TAG xPed = 5500012312 e nItemPed = 000040
2 - Quando campos C6_NUMPCOM e C6_ITEMPC estiverem preenchidos, os dados serão levados para o XML
> GAP256 | Alterar Pedido + Item do para 5500012312 + 000040

- Ponto de Entrada/VEIA060CAOA_PE.prw
Solução:
Alterado processo da rotina Pedido Venda Veículos (VEIA060) para que ao faturar um pedido, os títulos de contas a receber gerados no financeiro obedeçam a ordem de negociação informada no pedido de venda de veículos.
> GAP259 | Titulos Gerados no Sigavei com parcelas diferentes no Financeiro

- Integracoes/RgLog - SILT/ZWSR012.prw
- SIGAPEC/Funcao/ZPECF008.PRW
**Descrição: GAP258 - Inclusão de Semáforo no Processo da Onda
**
**Fonte:** ZWSR012 - Alterado
Ajuste01: implementada validação do Semáforo se o mesmo está criado devido ao processamento da Onda.
Ajuste02: implementado parâmetro CMV_PEC052, o mesmo esta como default F (Falso) criar o mesmo em Produção. Foi definido por Rosangela e Juarez que não será utilizado Semáforo de controle da RGLOG para o Protheus quando estiver realizando a integração RGLOG Conferência, implementado parâmetro CMV_PEC052 para poder habilitar a utilização deste semáforo ou não. 
**Fonte:** ZPECF008 - Alterado
. Ajuste01: Implementado no fonte ZPECF008 Criação de semáforo para controle de utilização da Onda, este Semáforo verificara a Empresa e Filial para validação, ou seja, caso a abertura seja em outra empresa e …
> GAP258 | Inclusão de Semáforo no Processo da Onda #632

- Ponto de Entrada/OX004APV_PE.prw
- SIGAPEC/Funcao/ZPECF008.PRW
GAP262|Problemas na Onda do Sigapec de Status e Errorlog
Descrição:
INC0120571 Colocar validação no campo do Modal do Orçamento para que não ocorra errorlog
Solução:
Variável _cModal não declarado causando erro quando não é informado o Modal na Integração
Ajuste no Fonte: OX004APV_PE
Descrição:
INC0120578 Está gerando o erro do anexo ao gerar a onda de picking das duas empresas, 02 e 90
Solução:
Variável _cGrupo não declarado causando erro quando não é informado o Modal na Integração
Ajuste no Fonte: ZPECF008
Descrição:
INC0120664 Estamos com vários orçamentos que já foram geradas ondas e o status não mudou para "S", ou seja, está em branco
Solução:
Ajustado no fonte a validação para preenchimento do campo de Status corretamente e não deixando-o em branco.
Ajuste no Fonte: ZPECF008
> GAP262|Problemas na Onda do Sigapec de Status e Errorlog.

- SIGAFAT/Função/nfesefaz.prw
GAP267 - Desconsiderar o array aICMSST qd nao houver imposto
Descrição: Rotina não encontra um ELEMENTO dentro da ARRAY na função NFEITEM, no fonte NFESEFAZ.PRW.
Ajuste no Fonte na linha 8611 para desconsidera o array aICMSST, quando nao houver o imposto
Especificação Técnica:Não Possui
Manual Técnico: Não Possui
Termo de Entrega: Não Possui
> GAP267 - Desconsiderar o array aICMSST qd nao houver imposto

- Ponto de Entrada/CBRETEAN_PE.prw
GAP283 | Realizar alteração na rotina ZWMS095 para atender ao processo de triagem de peças.
*Descrição: houve atualização da maneira que a informação é recebida fisicamente no processo, que antes o box continha um barcode com as informaçoes de LOTE|PRODUTO|QUANTIDADE. Essa mesma informação passou a vir em um QRCode, hoje nao tratado no sistema.
Especificação Técnica: [DEV19 - Especificação Funcional -movimentaçao de peças - WMSV095.pdf](https://github.com/user-attachments/files/17395718/DEV19.-.Especificacao.Funcional.-movimentacao.de.pecas.-.WMSV095.pdf)
Manual Técnico: Não Possui
Termo de Entrega: [Termo_Entrega - Transferencia de Produtos.pdf](https://github.com/user-attachments/files/17395746/Termo_Entrega.-.Transferencia.de.Produtos.pdf)
> Ajuste para receber a leitura do QrCode das etiquetas Hyundai
