Caoa-Montadora-de-Veiculos-Ltda/Protheus

SIGAPEC/Relatorio/ZPECR016.prw

Fonte: ZPECR016 - Rel Pedidos de Vendas
Erro: Melhoria -> Inclusão de filtros adicionais
Objetivo: Incluídos filtros individuais para os Status dos Itens, bem como para a seleção de um CNPJ

PEC056 - Ajuste relatório ZPECRC016 - Rel.Ped.Vendas

---

SIGAPEC/Relatorio/ZPECR016.prw

Fonte: ZPECR016 - Rel Pedidos de Vendas
Erro: Melhoria -> Inclusão de filtros adicionais
Objetivo: Incluídos filtros individuais para os Status dos Itens, bem como para a seleção de um CNPJ

CHG0032305 - PEC056 - Ajuste relatório ZPECRC016 - Rel.Ped.Vendas (#77)

---

SIGAPEC/Relatorio/ZPECR017_V2.prw

Revitalização completa do relatorio de produtos.

CHG0032286 - PEC058 - Revitalização do relatório ZPECR017 - Rel.Cad.Produto

---

Integracoes/MasterSaf/CMVMSF06.prw

**Ticket: INC0088345
Erro:**
Ao gera os arquivo SAFX 108 e 109,  esta levando algumas horas para gerar os arquivos
**Solução:**
Atualização das consultas na geração dos arquivos SAFX108 e 109 para melhoria do desempenho da geração dos arquivos
**Ticket: INC0088517
Erro:** 
Na geração dos arquivos da SAFX 112 e 113, esta ocorrendo o errorlog: Error : 904 - ORA-00904: "SF"."FT_NFISCAL": invalid identifier
**Solução:**
Correção na consulta da Geração do arquivo SAFX112 e 113, o qual foi corrigido o Alias na consulta da SAFX112.
**Termo de Entrega:**  [GAP-SAF002 - Geração dos arquivos SAFX 108 e 109 apresenta extrema demora e Error log na geração da SAFX112 e 113.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/11445552/GAP-SAF002.-.Geracao.dos.arquivos.SAFX.108.e.109.ap …

SAF002 - Contempla as seguintes Solicitações: INC0088345 e INC0088517

---

SIGAEIC/Funcao/CMVEIC01.prw
SIGAEIC/Funcao/ZEICF021.PRW

Fonte  ZEICF021.prw
ajustado a query principal para validar saldo entre as Tabela SW3, SW5 e EW5
Fonte CMVEIC01.prw
Alterado a ordem do Indice ta tabela temporaria

EIC132 - Ajuste na query para validação do saldo das Tabela SW3, SW5 e EW5

---

Ajustes/SIGAPEC/ZPECAJ01.prw
Genericos/Funcao/ZWSRFUN.PRW

Function ZPECAJ01
Correção: criação do fonte para realizar ajuste de estoque entre CAOA e RGLOG
Function ZWSRFUN
Correção: Ajuste validação campo SZK->(FieldPos("Z1_SERORI")) para SZ1->(FieldPos("Z1_SERORI")) >

CHG0032469 - PEC062 - Rotina para equalizar a conferencia Rglog e Protheus

---

SIGAEIC/Funcao/ZEICF021.PRW

Divergência já foi corrigido para montadora Anápolis, foi compatibilizado para que rode na Filial de Barueri.
Sendo realizados teste para confirmar a correção para ambas Empresas.

CHG0032479 - EIC135 - Compatibilização para Barueri

---

Ponto de Entrada/GFEXFB06_PE.PRW
Ponto de Entrada/GFEXFB18_PE.PRW
SIGAGFE/Funcao/ZGFEF007.PRW

Fonte GFEXFB006 
Melhoria: Criado variavel p/salvar o Valor do componente a totalizar no tipo TRT
Fonte GFEXFB018
Melhoria: PE p/ chamar a rotina ZGFEF007
Fonte ZGFEF007
Melhoria: Verificado cada componente para totalizar o tipo TRT

GFE101 - Ajuste no cálculo de novos componentes

---

Ponto de Entrada/ZCMV_NFESEFAZ_PE.prw
Ponto de Entrada/ZCSP_NFESEFAZ_PE.prw

Atualização a Consulta para pegar os dados da DI da tabela SW6, foi ajustado nos fontes para Anápolis e  Barueri

CHG0032498 - FAT121 - Atualização a Consulta para pegar os dados da DI da SW6

---

SIGAVEI/Função/CMVCOMVE.prw

Incluirão dos VV1_DI e VV1_DTDI para serem atualizados com as informações da DI

CHG0032497 - EIC136 - Inclusão numero Di e Data Di com as informações da DI

---

Ponto de Entrada/EICDI154_PE.PRW
SIGAWMS/Função/ZWMSF016.prw

**Fontes envolvidos**
EICDI154_PE.prw
ZWMSF016.prw
Ajustado o Ponto de Entrada EICDI154 para preencher o campo D1_XCASE ao gerar a NF pelo SigaEIC.
No fonte ZWMSF016.prw ajustado as consultas, relacionando os dados da dos itens do Documento de entrada (SD1) com os Dados das Invoice(SZM).
Devido o endereçamento de Unitizadores estar relacionado diretamente com o processo de importação ao qual na Importação da Invoice Antecipada preencher a tabela SZM, somente terá efeito para Processo que gerarem Documento de entrada após aplicação da GMUD.
Para Processos anterior a GMUD, verificar a possibilidade de estorno ou disponibilizar um ambiente sem atualizar o fonte ZWMSF016.prw

CHG0032528 - WMS115 - Endereçamento de Unitizadores

---

SIGACTB/Funcao/ZCTBF001.PRW

Foi reformulado a Query o qual melhorou o desempenho reduzindo o tempo de geração dos arquivos.
Incluído filtro para gerar Tabela de Preço por estado individualmente.

CHG0032550 - CTB001 - Ajuste na Query para melhor desempenho

---

Integracoes/MasterSaf/CMVMSF06.prw

Ajuste na Query na Geração do Arquivo SAFX2013, assim melhorando o Desempenho na geração do mesmo.
ajustado para Salvar os dados em arquivo periodicamente assim reduzindo a memória utilizado no processamento.

CHG0032548 - SAF003 - Ajuste na Query da Geração do SAFX2013

---

SIGAPEC/Relatorio/ZPECR017.prw

Fonte: ZPECR017
Melhorias:
Adicionado os campos de primeira e ultima compra e venda referentes ao legado.
Adicionado a data da primeira compra e venda na query do Protheus
Adicionado o campo da inclusão do cadastro do produto e ajustado campo de alteração
Ajustado para converter a data de string para data
Ajustado para 1a compra e venda trazer a menor data entre protheus e legado
Ajustado para ultima  compra e venda trazer a maior data entre protheus e legado
caoa-emariano committed 3 days ago

CHG0032544 - PEC064 - Primeira compra e venda - ZPECR017

---

Integracoes/Autoware/Montadora/CMVAUT01.PRW

Fonte: CMVAUT01.prw
Incluir Controle de transação na integração do Autoware.
Melhoria na geração de Log de erro, gravando o log em arquivo localizado no servidor na pasta /autoare/.log
[GAP028 - Portal Comercial – Integração Autoware.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12099848/GAP028.-.Portal.Comercial.Integracao.Autoware.pdf)

Integração | Autoware 100.001 | Melhoria na geração de Log de erro retorno do webservice (#GAP028)

---

SIGAPEC/Relatorio/ZPECR014.prw

Foi adicionando colunas de Cliente, Loja, Nome do Cliente e Status do Orçamento
Ajustado a consulta para trazer somente os orçamento abertos.
[GAP051 - Ajuste Rel Diverg pedido x cadastro.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12197584/GAP051.-.Ajuste.Rel.Diverg.pedido.x.cadastro.pdf)

CHG0032640 | PEC011.001 | Ajustes de coluna e na consulta

---

SIGAPEC/Funcao/ZPECF011.PRW
SIGAPEC/Funcao/ZPECFUNA.PRW

Fonte: ZPECF011
Erro: Desposicionamento da tabela VS1 causando validação incorreta de Status  
Objetivo: Alterado o momento da chamada de função que recalcula a TES Inteligente
Fonte: ZPECFUNA
Erro: Desposicionamento da tabela VS1 causando Recálculo de impostos dos Orçamentos incompletos
Objetivo: Regra para calcular todos orçamentos do Picking
Parâmetro: MV_MIL0095
Erro: Parâmetro não gravado corretamente
Objetivo: Ajustar o parâmetro para o valor 4 nos três idiomas

CHG0032689 | Integração | RgLog 003.002 | Ajuste no erro apresentado no momento da confirmacao

---

Integracoes/Autoware/Montadora/CMVAUT01.PRW

Fonte: CMVAUT01
Erro: Em alguns casos estava apresentando erro de falta de modelo.
Correção: Ajustado o fonte para sempre conectar na empresa 01 - Montadora Anapolis no momento do recebimento da integração

CHG0032697 | Integração | Autoware 100.005 | Erro na abertura da empresa no momento do recebimento

---

SIGAEIC/Funcao/CMVEIC01.prw
SIGAEIC/Funcao/ZEICF021.PRW

INC0093780
-
Fonte : ZEICF021, CMVEIC01
Ajustados os fontes para quando ocorrer erros, continuar a processar o arquivo
INC0094553
-
Fonte : ZEICF021
Foi ajustado o fonte para limpar a variável que pega a BL para ser preenchido novamente com o valor correto
INC0095011
-
Fonte : ZEICF021
Foi adicionado validação da Case quando o fornecedor estiver nos Parâmetros, CMV_EICHYU, CMV_EICHY2 e CMV_EICHY3, o qual será adicionados zeros à esquerda quando o tamanho for menor que 3 caracteres.
**Parâmetro:** CMV_EICHYU
**Tipo         :** Caracter
**Descrição:** Parâmetro para Ajuste da CASE com menos de 3 caracteres na Invoice Antecipada
**Conteúdo:** 00303301; 
**Parâmetro:** CMV_EICHY2
**Tipo         :** Caracter
**Descrição:** Parâmetro Auxiliar do CMV_EICHYU, caso necessário incluir mais …

CHG0032714 | EIC003.008 | Melhorias e ajustes da Invoice antecipada

---

SIGAWMS/Função/ZWMSF016.prw

Alteração da consulta que utiliza como base o campo D1_NUMSEQ para validar os registro, para utilizar o campo D0Q_ID o qual não se repete como base para a consulta.
[GAP074 - Erro no endereçamento causado por D1_NUMSEQ duplicado.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12432326/GAP074.-.Erro.no.enderecamento.causado.por.D1_NUMSEQ.duplicado.pdf)

CHG0032755 | WMS001.002 | Erro no endereçamento causado por D1_NUMSEQ duplicado

---

Integracoes/MasterSaf/CMVMSF06.prw

Correção na Consulta da SAFX109, para trazer somente as Ordens de Produção que tiverem movimentado matéria prima.
[GAP075 - SAFX109 é gerada na base DES, PRD não.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12433173/GAP075.-.SAFX109.e.gerada.na.base.DES.PRD.nao.pdf)

CHG0032756 | FIS003.004 | Correção na geracao da SAFX109 das ordens de producao

---

SIGAEIC/Funcao/ZEICF021.PRW

Ajuste de variável convertendo de caractere para Numérico o seu conteúdo.
[GAP078 - Inserção de Invoice Antecipada apresenta errorlog.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12501344/GAP078.-.Insercao.de.Invoice.Antecipada.apresenta.errorlog.pdf)

CHG0032781 | EIC003.010 | Ajuste no tratamento de tipo de variavel

---

Integracoes/SAP/CaoaSp/ZSAPF007.prw
Integracoes/SAP/Montadora/CMVSAP07.prw

Incremento no log no fonte CMVSAP07.prw
Inclusão das validações do fonte CMVSAP07.prw no fonte ZSAPF007.prw, deste forma prevenindo futuros erros na integração de Franco da Rocha.

CHG0032794 | Integração | SAP 002.001 | Forçar a conexão com a empresa corrente

---

SIGAWMS/Função/ZWMSF003.prw
SIGAWMS/Função/ZWMSF019.PRW

FONTE: ZWMSF003
MELHORIA: Incluído a chamada do programa fontes ZWMSF019
FONTE:ZWMS019
MELHORIA: Efetua a leitura de um .CSV e alimentar a tabela SZJ.

CHG0032809 | WMS002 | Importação dos unitizadores para transferência

---

SIGACTB/Funcao/CMVCTBCUS.prw

Contabilizar o CPV(LP 678) na rodada da produção, pois neste recálculo os custos indiretos são apurados.

CHG0032882 | CTB002.001 | Ajuste no CPV da LP678

---

Integracoes/Autoware/Montadora/CMVAUT04.PRW
Ponto de Entrada/MS520DEL_PE.PRW
SIGAFAT/Função/ZFATF019.prw

Fonte: ZFATF019.prw
Correção do erro no gatilho C6_OPER e Ordenar pedidos por de número/item
Correção no estorno dos empenhos
Fonte: CMVAUT04.PRW
Ajuste para enviar os Status para o Autoware pelo rotina ZFATF019
Fonte: MS520DEL_PE.prw
Correção na exclusão da NF para Estornar os empenhos corretamente
Termo de Entrega:
[GAP087 - PORTAL FATURAMENTO erro de gatilho C6_OPER e Ordenar pedidos por de número-item.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12751492/GAP087.-.PORTAL.FATURAMENTO.erro.de.gatilho.C6_OPER.e.Ordenar.pedidos.por.de.numero-item.pdf)

CHG0032869 | FAT003.002 | Ajuste no gatilho C6_OPER e ordenar pedidos por de número e item

---

SIGACOM/Função/ZCOMF051.prw
SIGAWMS/Função/ZWMSF016.prw

Fonte: ZCOMF051.prw
Incluído na rotina validação para preencher o Campo D1_XCASE na importação do CSV do processo CKD ao importar pela rotina de Pré-Documento.
Fonte: ZWMSF016.PRW
Ajustes na rotina para não remover espaços em branco de campos de tabela, o qual provoca erro ao não encontrar o registro correto.
Ajuste para processar os Unitizadores CKD.
***Termo de Entrega: ***
[GAP086 - Melhoria de importação do CSV. A rotina não alimenta tabela SD1 coluna D1_XCASE.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12730849/GAP086.-.Melhoria.de.importacao.do.CSV.A.rotina.nao.alimenta.tabela.SD1.coluna.D1_XCASE.pdf)

CHG0032868 | WMS001.004 | Melhoria na importação do CSV, alimentar tabela SD1 e coluna D1_XCASE

---

Integracoes/MasterSaf/CMVMSF06.prw

INC0095948
- Foi desenvolvido uma função para retornar a Conta Contábil da Tabela CT2.
INC0096374
1. SAFX 108
- Para o 'TIPO', conforme Layout não é possível incluir Campos que não exista no arquivo.
- Foi criado um filtro na consulta para trazer somente tipo 'PA'
2. SAFX 109
- Foi criado um filtro na consulta para trazer os tipo diferentes de 'PA'.
INC0099202
- Foi criado validação para trazer as CFOP's 1352 e 2352, na extração da CT-es corretamente.
- Pois existia um conflito entre as Empresas Anápolis e Franco da Rocha.
INC0099616
- Foi implementado um De-Para para as CST PIS COFINS 01 e 02 - Operação Tributável com Alíquota Diferenciada e que possua valor PIS COFINS ST para gerar no arquivo com a CST – 05 Operação Tributável por Substituição Tributária no campo próprio CST ST ZFM. …

CHG0032933 | FIS003.005 | Ajuste nos Arquivos MasterSaf SAFX07, SAFX09, SAFX108 e SAFX109

---

Ponto de Entrada/MT110TEL_PE.PRW
Ponto de Entrada/MT110TOK_PE.PRW
SIGACOM/Função/ZCOMF055.prw
SIGACOM/Função/ZCOMF056.prw

**Fonte:** MT110TOK - Alterado
**Ajuste:** Ponto de entrada acionado ao salvar a solicitação de compras.
**Fonte:** ZCOMF055 - Novo
**Ajuste:** Fonte responsável para verificar se o código de comprador e um usuário bloqueado.  
**Fonte:** ZCOMF056 - Novo
**Ajuste:** Fonte responsável por consulta padrão específica dos códigos de compradores desbloqueados.

CHG0032929 | COM004 | Validação do comprador desligado

---

SIGAFAT/Relatorio/ZFATR004.prw

Rel Fat X Tit Inclusão do Campo de Forma de Pagamentos e a Desc. Forma. Pagto
[GAP100 - Rel Fat X Tit Pendentes venha com informação do Campo - VRL_XFORMA.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13380871/GAP100.-.Rel.Fat.X.Tit.Pendentes.venha.com.informacao.do.Campo.-.VRL_XFORMA.pdf)

CHG0033018 | FAT007.001 | Inclusão do Campo - VRL_XFORMA

---

Integracoes/MasterSaf/CMVMSF06.prw

Implementada função para pegar a Conta Contábil da CT2 na geração do arquivo da SAFX08.
Correção da query para trazer somente o Produto Acabado da Ordem de Produção na geração do arquivo da SAFX108.
Correção da query para trazer somente os componentes da Ordem de Produção na geração do arquivo da SAFX109.
Orientação para gerar o arquivo SAFX52 com a data do dia do fechamento do Estoque.
[GAP099 - Ajuste nos arquivos SAFX08, SAFX108, SAFX109 e SAFX52.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13311602/GAP099.-.Ajuste.nos.arquivos.SAFX08.SAFX108.SAFX109.e.SAFX52.pdf)

CHG0033009 | FIS003.006 | Ajuste nos arquivos SAFX08, SAFX108, SAFX109 e SAFX52

---

SIGAPEC/Funcao/ZPECFUNA.PRW

Alterado a Consulta De:
SELECT  FM_CLIENTE, FM_LOJACLI, FM_TIPO  
FROM SFM020 WHERE  
FM_FILIAL  = '2020012001' 
AND  FM_CLIENTE = '000096' 
AND  FM_LOJACLI = '01' 
AND D_E_L_E_T_ = ' ' OR (FM_EST = 'SP' AND FM_CLIENTE = ' ') 
ORDER BY FM_CLIENTE DESC 
Para :
SELECT
SFM.FM_CLIENTE,
SFM.FM_LOJACLI,
SFM.FM_TIPO
FROM SFM020 SFM
WHERE
SFM.FM_FILIAL  = '2020012001' AND
SFM.D_E_L_E_T_ = ' ' AND
(
( SFM.FM_CLIENTE = '000096' AND
SFM.FM_LOJACLI = '01 ' 		
) OR
( SFM.FM_EST     = 'MS ' AND
SFM.FM_CLIENTE = ' '
)
)
ORDER BY SFM.FM_CLIENTE DESC
Desta forma removendo or registros Deletados da Consulta.
[GAP102-Os pedidos subiram com o tipo de operação errado para o SIGAPEC.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13395594/GAP102-Os.pedidos.subiram.com …

CHG0033025 | PEC001.008 | Ajuste na ZF para operações 92

---

Integracoes/Autoware/Montadora/CMVAUT04.PRW
Ponto de Entrada/MACSOLICMS_PE.prw
SIGAFAT/Função/ZFATF019.prw

INC0095676
Solução:
Foi alterado para que quando for editado um campo atualizar somente a linha que está sendo alterada e não mais a tabela inteira
INC0095679
Solução:
Habilitado o campo de Valor de Movimentação para ser editável e recalcular os valores da linha.
INC0087083
Solução:
Foi incluído a função de envio ao Autoware após a Geração da do Documento de Saida.
INC0091464
Solução:
Foi incluído a função de envio ao Autoware após a Geração da do Documento de Saida.
INC0100967
Solução:
Foi criado uma variável para salvar os dados na inicialização da rotina o qual é utilizado para realizar o Rollback no momento de cancelar o processo ou realizar o faturamento os itens não faturados também serão realizado o Rollback
INC0100107
Solução:
Foi criado um tratamento na busca dos chassis conforme …

CHG0033037 | FAT003.003 | Pacote de melhorias gerais no portal

---

Ponto de Entrada/MA110BUT_PE.PRW

**Fonte:** MA110BUT_PE - Alterado
**Ajuste:** Remover comentário que limpava o array do botão da enchoice bar.

CHG0033031 | COM005 | Habilitar a tela de aprovadores de solicitação de compras

---

SIGAFAT/Relatorio/ZFATR004.prw

Ajuste no Fonte - ZFATR004.PRW - GAP100- Rel Fat X Tit Inclusão do Campo de Forma de Pagamentos
ajustando a consulta para evitar a duplicidade de dados

CHG0033046 | FAT007.002 | Duplicidade ao trazer os campos forma e descrição do pagamento

---

SIGAFIS/Relatorio/ZFISR011.prw

Ajustes no fonte para correção da consulta que está gerando o errorlog
adicionando campos que ficaram faltando na clausula do Group By da consulta.
[GAP110 - THREAD ERROR.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13674539/GAP110.-.THREAD.ERROR.pdf)

CHG0033109 | FIS002.004 | Ajuste no errorlog ao gerar o relatorio

---

Integracoes/Autoware/Montadora/CMVAUT01.PRW
Ponto de Entrada/MT089CD_PE.prw

Criação de validação para verificar se a rotina foi chamada pelo webservice.
Posicionamento do produto em tempo de execução, pois está desposicionando a tabela de produto.
Alteração na ordem do Array dos itens do Pedido para ser que os gatilhos sejam executados de maneira correta na inclusão da rotina automática.

CHG0033172 | Integração | Autoware 100.006 | Ajuste na TES Inteligente, veículos importado com Origem 6 e 1

---

SIGAFIS/Função/ZFISF008.prw
SIGAFIS/Relatorio/ZFISR011.prw
SIGAFIS/Relatorio/ZFISR016.prw
SIGAFIS/Relatorio/ZFISR017.prw

**Fonte:** ZFISF008 - Novo
**Ajuste:** Tela para escolher entre os relatórios de NF de entrada e saída.
**Fonte:** ZFISR016 - Novo
**Ajuste:** Relatório de NF de entrada com chave gerada.
**Fonte:** ZFISR017 - Novo
**Ajuste:** Relatório de NF de saída com chave gerada.
**Fonte:** ZFISR011 - Alterado
**Ajuste:** Alterado o nome do relatório, estava com valor errado.

CHG0033168 | FIS005 | Relatório de notas fiscais financeiro (GAP105) #324

---

SIGAPEC/Relatorio/ZPECR022.prw

Inclusão do Campo Descrição do Produto no Relatório.
Foi incluído uma barra de progresso na geração do relatório para o usuário ter um feedback na geração.
***Termo de Entrega***
[GAP133 - Incluir no relatório ZPECR022 o campo Descrição do Item do cadastro do produto .pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14389754/GAP133.-.Incluir.no.relatorio.ZPECR022.o.campo.Descricao.do.Item.do.cadastro.do.produto.pdf)

CHG0033342 | PEC002.002 | Ajuste no campo Descrição do Item

---

SIGAPEC/Relatorio/ZPECR017.prw

Ajustado a Consulta onde nas situações que ocorrer divisão por zero, será considerado zero.

GAP141 | Dificuldades para extrair relatório de cadastro geral das pelças

---

Ponto de Entrada/GFEA065_PE.prw

Ajuste da TES ao atualizar o Fiscal do Documento de Frete, conforme o Documento de entrada através do ponto de entrada MVC GFEA065 com o ID FORMCOMMITTTSPOS para atualizar a Tabela GW3 com a TES da Tabela SD1.

CHG0033399 | GFEA065.001 | Gravação da TES no Documento de Frete

---

Ponto de Entrada/M410PVNF_PE.prw
SIGAFAT/Função/ZFATF014.PRW

Alteração no ponto de entrada M410PVNF_PE.prw a exibição de mensagem da liberação de crédito, para aparecer somente quando o Credito for negado, e alteração para uma função mais atual para exibição de mensagens.
Alteração do fonte ZFATF014.prw, removendo funções no momento da gravação da Tabela SA1, e reposicionando antes da gravação da tabela.

CHG0033413 | Travamento na Avaliação de Credito do Cliente

---

SIGAFAT/Função/ZFATF019.prw

Incluído o Filtro De Data Até Data de inclusão do pedido na Tela de Faturamento Atacado.
Inclusão de Consulta padrão nos Campo de Segmentos do filtro.

CHG0033422 | FAT003.004 | Melhoria no filtro para informar data digitação e consulta padrão no campo segmento

---

Ponto de Entrada/MA140BUT_PE.PRW
SIGACOM/Função/ZCOMF051.prw

CHG0033430 | EIC001.001 | Inclusao itens Pre documento de entrada Franco da Rocha

---

Integracoes/RgLog - SILT/ZWSR003.prw
Integracoes/RgLog - SILT/ZWSR004.PRW
SIGAPEC/Funcao/ZPECF004.PRW

…ados na validação em ambiente de desenvolvimento - Release 12.1.2310

CHG0033436 | Release | 12.1.2310 | Fontes compatibilizados para nova versão

---

SIGAPEC/Relatorio/ZPECR025.prw

Desenvolvido o Relatório de Divergência WIS x Protheus.

CHG0033432 | PEC014 | Relatório de divergência picking WIS, códigos cortados

---

SIGAPEC/Funcao/ZPECF040.prw

Foi atualizada a Query para que o cálculo tiver um divisor que ZERO, que o resultado será ZERO para prevenir erros na consulta.

CHG0033463 | PEC013.003 | ORA-01476: divisor is equal to zero

---

Integracoes/SERPRO/CVMSER01.prw

Fonte: CVMSER01
Erro: Enviando código de tipo Montagem e tipo de carroceria errado para o SERPRO 
Correção01: Alterado programa para a geração do arquivo para enviar código de veículo conjugado de 
acordo com parâmetros criados para a validação.

CHG0033450 | Integração | SERPRO 002 | Tratamento no arquivo SERPRO para caminhões HR e HD

---

Integracoes/Autoware/Montadora/CMVAUT02.PRW

Atualização da Consulta para Atender o Portal  Comercial.

CHG0033490 | FAT003.005 | Erro ao realizar Faturamento no Portal não está refletindo as baixas no AutoWare

---

SIGAFAT/Função/ZFATF019.prw

Foi criado validações para somente pegar números de Chassis disponíveis, assim se houver algum Chassi amarrado no SIGAVEI será ignorado pelo Portal Comercial.
Acrescentado um Parâmetro para que o usuário limite a quantidade de chassis que será faturado.

CHG0033585 | FAT003.005 | Ajuste na amarração dos chassis para PCD

---

Integracoes/RgLog - SILT/ZWSR010.PRW
SIGAEIC/Funcao/CMVEIC01.prw

INC0113459
Inclusão da variável cCnpj como parâmetro da Função ZWSR007ITE no fonte ZWSR010.PRW 
INC0113493
Erro ao tentar importar o arquivo de invoice antecipada.
Criação da Variável CFILEXEC na rotina  MONTAWORK1 no fonte CMVEIC01.PRW

CHG0033605 | OneGate002 | Ajuste nos errorlog de tratamento da empresa

---

Ponto de Entrada/VEIA060CAOA_PE.prw

desenvolvido uma função o qual irá preencher o campo E1_XFORMA no final do Faturamento do veiculo no SIGAVEI pela rotina VEIA060.

CHG0033608 | VEI004 | Ajuste da Forma de Pagamento para PCD

---

Ponto de Entrada/GFEA0651_PE.PRW
Ponto de Entrada/GFEA0652_PE.PRW
SIGAGFE/Funcao/ZGFEF005.prw

A atualização do Fiscal ERP estava considerando a melhoria, porém a Integração Doc Frete (Lote) não, pois não chama a função padrão na sua totalidade.
Foi desenvolvido dois pontos de entrada para atender a melhoria.

CHG0033626 | GFE004 | Atribuindo código TES errado produto FR003

---

SIGAFAT/Função/nfesefaz.prw

Fonte: NFESEFAZ
Ajustado o fonte para considerar a FCI das HR

OneGate003 | Inclusão do código FCI nas vendas de veiculos

---

Genericos/Funcao/ZMSBLQUSR.prw
Integracoes/Protheus/ZWSR017.PRW

**Fonte:** ZWSR017 - Novo
**Ajuste:** Integração com API Rest Users padrão do Protheus para consultar dados e o bloquear usuários.
**Fonte:** ZMSBLQUSR- Alterado
**Ajuste:** Bloqueia usuário do Protheus

CHG0033589 | CFG002.001 | Adequação da nova API de bloqueio de usuários

---

Ponto de Entrada/GFEXFB06_PE.PRW
SIGAGFE/Funcao/ZGFEF007.PRW

Correção do ponto de entrada do cálculo do TRT quando a faixa de excedente cai no mínimo.

CHG0033635 | GFE001.001 | Ajuste na relação de TRT

---

SIGAPEC/Funcao/ZPECFUNA.PRW

Foi alterado o filtro para poder excluir as NF-e nas seguintes situações
D -- NF DENEGADA
N -- NF NÃO AUTORIZADA
S -- NF AUTORIZADA

CHG0033643 | PEC016 | Não está permitindo excluir Nota denegada

---

SIGAFIS/Relatorio/ZFISR001.prw
SIGAFIS/Relatorio/ZFISR003.prw

Foi corrigido a pesquisa ao qual faz para pegar as informações de ISS, o qual inicialmente pegava as notas de entrada do tipo RPS, no entanto deveria pegaras notas do Tipo NFS também.

FIS002.007 | CHG0033670 | Os relatórios customizados ZRFIS001 e ZRFIS003 estão levando valor de ISS para a coluna de valor de ICMS

---

SIGAPEC/Funcao/ZPECF030.PRW
SIGAPEC/Funcao/ZPECF033.prw

**Fonte:** ZPECF030 - Alterado
**Ajuste:** Identação e correções ortográficas
**Fonte:** ZPECF033 - Alterado
**Ajuste:** Adicionado campo de Dt. Digitação no início da grid e na query e movimentado Dt. Emissão para o final da grid.

CHG0033680 | PEC004.004 | Ajuste na tela de Consulta pecas, doc de entrada

---

SIGAFAT/Função/ZFATF019.prw
SIGAFAT/Função/ZFATF025.PRW
SIGAFAT/Função/ZFATF026.PRW
SIGAFAT/upd/GAP167_Previsao_Faturamento/XUPDPREV.prw

**Fonte**: 
**ALTERAÇÃO : ZFATF019**
AJUSTE: Alterado lógica para entender processo de Faturamento automatico
**NOVO: ZFATF025**
AJUSTE: Visualização/Alteração/Inclusão Previsão cabeçalho e item
**NOVO: ZFAT026**
AJUSTE: visualização dos itens, alteração da quantidade Liberada
**XUPDPREV**
AJUSTE: Atualização base
**Recurso: CAOA**

CHG0033709 | FAT003.006 | Previsão de Faturamento

---

README.md
SIGAPEC/Funcao/ZPECF013.prw

Foi ajustado o fonte ZPECf013 incluindo a Include FWMVCDef.ch que contém as definições e constantes utilizadas em MVC.
Será necessário realizar a Manutenção do Profile do Usuário.

CHG0033723 | PEC001.010 | Na Empresa 90 HMB, ao Faturar um picking em seguida do outro ocorre errorlog

---

Ponto de Entrada/VM011DNF_PE.PRW
Ponto de Entrada/VX001DNF_PE.prw
SIGAEIC/Funcao/ZEICF033.prw
SIGAVEI/Função/CMVVEI03.PRW

GAP193 | Tag cCor no XML da nota fiscal, para constar com os 4 dígito

CHG0033732 | FIS006 | Tag cCor no XML da nota fiscal, para constar com os 4 dígito

---

SIGAEIC/Funcao/CMVEIC01.prw

Alteração na criação da tabela temporária de DbUseArea para FWTemporaryTable, na função MontaWork1 do fonte CMVEIC01.prw na linha 817.

CHG0033742| EIC003.013 | Erro ao integrar invoice antecipada - CBU Chery

---

Ponto de Entrada/VEIA060CAOA_PE.prw

Melhoria na Consulta para relacionar as Tabela VS9, VRL e SE1 para reordenar a ordem das parcelas entre o financeiro e a negociação do veículo, assim ficando correto a Forma de pagamento para ser integrado ao SAP.

GAP202 | Correção da Parcela financeira de integração com o SAP.

---

Ponto de Entrada/GFEA042_PE.prw

GAP203 | GFEA042.001 | PE para chamar a função ZGFEF008 - Alterar peso bruto
Criado este PE neste gap por não ter subido no GAP032 - Alterar peso que é o GAP original
*Especificação Técnica:* Não possui
*Manual Técnico:* Não Possui
*Termo de Entrega:* Não Possui
Recurso: Caoa

GFEA042.001 | PE para chamar a função ZGFEF008 - Alterar peso bruto

---

SIGAPEC/Funcao/ZPECF013.prw

Correção do semáforo para liberação do faturamento quando há concorrência entre Empresas e Filiais

GAP204 | Correção no Controle de Semaforo

---

Ponto de Entrada/VEIA060CAOA_PE.prw

Incluído uma tratativa para balancear as tabelas VRL (Negociação), SE1(Contas a Receber) e VS9(Relacionamento entre VRL e SE1) para preenchimento do campo da Placa no Título gerado no Contas a Receber para a integração com o SAP.

GAP206 | Integração do SAP para Título de Veículo PNE sem Placa

---

SIGAPEC/Funcao/ZPECF008.PRW

GAP208 | O pedido foi atendido parcialmente e foi fechado, não gerando BO

GAP208 | O pedido foi atendido parcialmente e foi fechado, não gerando BO

---

Integracoes/RgLog - SILT/ZWSR003.prw

Melhoria para diferenciação do Log da Geração do Romaneio para as empresas 02 e 90

WSR003.001 | Diferenciação do Log para as Empresas

---

Ponto de Entrada/CRMA980_PE.PRW

Ajuste no Fonte para validação da Empresa para criação da Tabela SZ7.

GAP213 | Ajuste no Fonte para validação da Empresa para criação da Tabela SZ7.

---

SIGACOM/Função/ZCOMF029.prw
SIGACOM/Relatorio/ZCOMR001.PRW
SIGACOM/Relatorio/ZCOMR004.PRW

Alterado as rotinas ZCOMR004 e ZCOMR001 para serem executadas como JOB através do fontes ZCOMF029 na aprovação do pedido de compra

GAP214 | Lentidão na rotina de aprovação do Pedido de Compras

---

Genericos/Funcao/ZRESTSA1.PRW
Genericos/Funcao/ZWSRFUN.PRW
Integracoes/Protheus/ZRESTSA1.PRW
Integracoes/Protheus/ZWSR016.PRW

GAP136 | API Cadastro de Cliente
Descrição: API Cadastro de Cliente - Mapear os campos necessários para criar a API de clientes (REST).
Anexo Planiha para o preenchimento das colunas referente ao segmento Autoware, onde as concessionárias possam preencher e realizar a integração para o Protheus.
Especificação Técnica: [Mapeamento - API Clientes - V2.xlsx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14408446/Mapeamento.-.API.Clientes.-.V2.xlsx)
Manual Técnico: [GAP136 API Cadastro de Cliente_Validação_V2.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14574663/GAP136.API.Cadastro.de.Cliente_Validacao_V2.docx)
Termo de Entrega: [GAP136 API Cadastro de Cliente_Termo.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14574685/G …

Gap136 | API Cadastro de Cliente

---

Ponto de Entrada/M110STTS_PE.PRW
Ponto de Entrada/MT120FIM_PE.prw
Ponto de Entrada/MT120OK_PE.PRW
Ponto de Entrada/MT125OK_PE.PRW
SIGACOM/Função/ZCOMF015.PRW

Alteração da Rotina ZCOMF015, para ser executada via JOB através dos pontos de entrada M110STTS_PE, MT120FIM_PE, MT120OK_PE e MT125OK_PE.

GAP222 | Performance na rotina de Solicitação de Compras.

---

SIGAFAT/Função/danfeii.prw

Correção A da rejeição do indicador de desoneração inválido para a ZFM [nItem:1]

GAP227 | A nota 000141488 está com a rejeição

---

SIGAPEC/Funcao/ZPECF011.PRW

Ao confirmar a movimentação, quando há Saldo em estoque no Protheus e no WIS o saldo esta zerado estava validando erroneamente considerando que o havia mais saldo nos dois armazéns.

PEC011.002 | Erro ao enviar a confirmação da separação - errorCode : 999

---

SIGAFAT/Função/danfeii.prw
SIGAFAT/Função/nfesefaz.prw

GAP227 | A nota 000141488 está com a rejeição  -- Correção Emergencial

GAP227 | A nota 000141488 está com a rejeição  -- Correção Emergencial

---

Genericos/Funcao/ZGENFTE90.prw

GAP224 - Atualização para entender filial D1 e D2
*Descrição: Atualização para entender filial D1 e D2
Especificação Técnica: Não possui
Manual Técnico: Não Possui
Termo de Entrega: Não Possui

ZGENFTE.001|Atualização para entender filial D1 e D2

---

Genericos/Funcao/ZGENFTE90.prw

Ajustes para emissão de notas entre as filiais da empresa 90 HMB.

FAT001.001|Ajustes para emitir as notas de retorno das filiais da empresa 90 HMB

---

SIGAFAT/Função/nfesefaz.prw

Rejeição 610 - erro na somatória do valor da NF.
Compatibilização do fonte TOTVS x CAOA Customizado – NfeSefaz.prw
Prazendo a função customizada RetNT2005 que substitui as regras do Padrão referente a NT 2020.005

GAP235 | Rejeição 610 - erro na somatória do valor da NF

---

SIGAFIS/Relatorio/ZFISR001.prw

GAP238! - IS002.008 - Incluídos campos de retenção de CSL
*Especificação Técnica:* Não possui
*Manual Técnico:* Não Possui
*Termo de Entrega:* Não Possui

FIS002.008|Incluídos campos de retenção de CSL

---

SIGAFIS/Função/ZFISF004.prw
SIGAFIS/Relatorio/ZFISR001.prw
SIGAFIS/Relatorio/ZFISR003.prw
SIGAFIS/Relatorio/ZFISR004.prw
SIGAFIS/Relatorio/ZFISR005.prw
SIGAFIS/Relatorio/ZFISR006.prw

*Nome Original do GAP* 
GAP198  - Adicionar ao relatório filtro com usuário de inclusão deate e filtro com NF separado por - Original
GAP201 | Inclusão de campo de grupo de cliente no relatório fiscal
*Descrição:* Incluido o grupo tributário do cliente/fornecedor e a seleção de notas fiscais
*Especificação Técnica:* 
[ESPECIFICAÇÃO RELATÓRIO (1).docx](https://github.com/user-attachments/files/16625357/ESPECIFICACAO.RELATORIO.1.docx)
*Manual Técnico:* Não Possui
*Termo de Entrega:* 
[Termo de Entrega - GAP198  - Adicionar ao relatório filtro com usuário de inclusão deate e filtro com NF.docx](https://github.com/user-attachments/files/16625361/Termo.de.Entrega.-.GAP198.-.Adicionar.ao.relatorio.filtro.com.usuario.de.inclusao.deate.e.filtro.com.NF.docx)

GAP198  - Adicionar ao relatório filtro com usuário de inclusão deate e filtro com NF separado por - Original

---

SIGAPEC/Classes/SaldoCAOAPEC.PRW
SIGAPEC/Funcao/ZPECF008.PRW
SIGAPEC/Funcao/ZPECFUNA.PRW

Correção da onda para gerar picking quando o saldo da peça similar é menor que o saldo da solicitada

GAP252 |  Correção da onda para gerar picking quando o saldo da peça similar é menor que o saldo da solicitada

---

SIGACOM/Relatorio/ZCOMR004.PRW

GAP257 | Pedido aprovado está calculando no Valor total de pedido somente a última linha do pedido

---

Integracoes/SERPRO/CVMSER01.prw
SIGAVEI/Função/ZVEIF006.PRW

Descrição: GAP190 | Importar um arquivo csv com todos os chassis na rotina de integração com SERPRO (CVMSER01).
Especificação Técnica: Não possui
Manual Técnico: [Manual_Técnico - Importar arquivos CSV.pdf](https://github.com/user-attachments/files/16998408/Manual_Tecnico.-.Importar.arquivos.CSV.pdf)
Termo de Entrega: [Termo_Entrega - GAP 190.pdf](https://github.com/user-attachments/files/16998418/Termo_Entrega.-.GAP.190.pdf)

GAP190 | Importar um arquivo csv com todos os chassis na rotina de integração com SERPRO (CVMSER01).

---

SIGAPEC/Funcao/ZPECF008.PRW
SIGAPEC/Funcao/ZPECFUNA.PRW

…
Correção da onda para gravar o Status correto no orçamento

GAP265 | Estamos com vários orçamentos que já foram gerado ondas e o status não mudou para "S", ou seja, está em branco

---

SIGAPEC/Funcao/ZPECF008.PRW
SIGAPEC/Funcao/ZPECF013.prw
SIGAPEC/Funcao/ZPECFUNA.PRW

GAP271.1|Onda SigaPec

---

SIGAPEC/Funcao/ZPECF035.prw

GAP285 | Lentidão no relatório de BO
